PRACTICAL NO 7 To apply Support Vector Machine for classification and analyze the impact of different kernels on model accuracy.

HARSHITA CS23156

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
path ="/content/drive/MyDrive/ML_Dataset/pulsar_stars.csv"
df=pd.read_csv(path)
df.head(5)

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0

In [8]:
df.shape

(17898, 9)

In [9]:
df.columns

Index([' Mean of the integrated profile',
       ' Standard deviation of the integrated profile',
       ' Excess kurtosis of the integrated profile',
       ' Skewness of the integrated profile', ' Mean of the DM-SNR curve',
       ' Standard deviation of the DM-SNR curve',
       ' Excess kurtosis of the DM-SNR curve', ' Skewness of the DM-SNR curve',
       'target_class'],
      dtype='object')

In [10]:
df.isnull().any().any()

np.False_

In [11]:
X = df.drop(columns=['target_class'])
y = df['target_class']

In [12]:
X.head()

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306

In [13]:
X = pd.get_dummies(X,dtype = int)

In [14]:
X.head()

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306

In [15]:
x =df.iloc[:, :-1]
y =df.iloc[:, -1]

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,test_size=0.3,random_state=42)
X_train.shape,X_test.shape

((12528, 8), (5370, 8))

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
X_train

array([[ 0.39398903,  0.27225212, -0.09759786, ..., -0.40338108,
        -0.19481754, -0.37780071],
       [-1.32725743, -1.52127273,  0.21878252, ..., -0.44578706,
         0.23837256, -0.02857034],
       [ 0.76130595,  0.98636783, -0.3245843 , ..., -0.2004973 ,
         0.038556  , -0.29531727],
       ...,
       [ 0.19435365, -0.48635278,  0.17242235, ..., -0.75001383,
         1.92294752,  1.91898259],
       [ 0.95911539,  0.50175114, -0.53401036, ..., -0.24457614,
        -0.20616758, -0.4040674 ],
       [ 0.37725131,  0.58093396, -0.12507761, ..., -0.74159513,
         2.05677923,  2.08022728]])

In [19]:
X_test

array([[ 0.22843774,  0.35277695, -0.27522748, ..., -0.43728381,
        -0.04649179, -0.25085816],
       [-1.38112247, -1.78437423,  1.44956147, ..., -0.22432742,
        -0.28338031, -0.46408179],
       [-0.30260453,  0.0698727 ,  0.02318325, ..., -0.54553131,
         0.21981851, -0.00614623],
       ...,
       [ 0.97889633,  0.3533328 , -0.46793554, ..., -0.3882352 ,
        -0.10691249, -0.33847727],
       [-0.17691945,  0.37417406, -0.21925266, ..., -0.55602557,
         0.1487237 , -0.05046816],
       [-0.01410706, -1.21585526, -0.01840983, ..., -0.20872688,
        -0.52776711, -0.61373985]])

In [20]:
y_test

15985    0
8188     1
8157     0
2589     1
11909    0
        ..
12653    0
6454     0
530      0
1540     0
6921     1
Name: target_class, Length: 5370, dtype: int64

In [21]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc=SVC()
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print(f'Model accuracy score with default hyperparameters:\n{accuracy_score(y_test,y_pred):.4f}')

Model accuracy score with default hyperparameters:
0.9790

In [22]:
svc=SVC(C=100.0)

In [23]:
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with rbf kernel and C=100.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernel and C=100.0: 0.9803

In [24]:
linear_svc=SVC(kernel='linear',C=1.0)
linear_svc.fit(X_train,y_train)
y_pred=linear_svc.predict(X_test)
print('Model accuracy score with linear kernel and C=1.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

Model accuracy score with linear kernel and C=1.0: 0.9788

In [25]:
linear_svc=SVC(kernel='linear',C=100.0)
linear_svc.fit(X_train,y_train)
y_pred=linear_svc.predict(X_test)
print('Model accuracy score with linear kernel and C=100.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

Model accuracy score with linear kernel and C=100.0: 0.9786

In [26]:
linear_svc=SVC(kernel='linear',C=1000.0)
linear_svc.fit(X_train,y_train)
y_pred=linear_svc.predict(X_test)
print('Model accuracy score with linear kernel and C=1000.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

Model accuracy score with linear kernel and C=1000.0: 0.9786

In [27]:
poly_svc=SVC(kernel='poly',C=1.0)
poly_svc.fit(X_train,y_train)
y_pred=poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and C=1.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

Model accuracy score with polynomial kernel and C=1.0: 0.9769

In [28]:
poly_svc=SVC(kernel='poly',C=100.0)
poly_svc.fit(X_train,y_train)
y_pred=poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and C=100.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

Model accuracy score with polynomial kernel and C=100.0: 0.9793

In [30]:
poly_svc=SVC(kernel='poly',C=1000.0)
poly_svc.fit(X_train,y_train)
y_pred=poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and C=1000.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

Model accuracy score with polynomial kernel and C=1000.0: 0.9793

In [31]:
sigmoid_svc=SVC(kernel='sigmoid',C=1.0)
sigmoid_svc.fit(X_train,y_train)
y_pred=sigmoid_svc.predict(X_test)
print('Model accuracy score with sigmoid kernel and C=1.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

Model accuracy score with sigmoid kernel and C=1.0: 0.8773

In [32]:
sigmoid_svc=SVC(kernel='sigmoid',C=100.0)
sigmoid_svc.fit(X_train,y_train)
y_pred=sigmoid_svc.predict(X_test)
print('Model accuracy score with sigmoid kernel and C=100.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

Model accuracy score with sigmoid kernel and C=100.0: 0.8773

In [33]:
sigmoid_svc=SVC(kernel='sigmoid',C=1000.0)
sigmoid_svc.fit(X_train,y_train)
y_pred=sigmoid_svc.predict(X_test)
print('Model accuracy score with sigmoid kernel and C=1000.0: {0:.4f}'.format(accuracy_score(y_test,y_pred)))

Model accuracy score with sigmoid kernel and C=1000.0: 0.8773

In [34]:
from sklearn.metrics import confusion_matrix
print('Confusion Matrix')
cm=confusion_matrix(y_pred,y_test)
print(confusion_matrix(y_pred,y_test))

Confusion Matrix
[[4556  331]
 [ 328  155]]